version: '3.7'

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    build:
      context: ./caddy
    ports:
      - '8080:8080'
    volumes:    
      - myshare:/srv
    networks:
      - react-express

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017

  api:
    image: api
    container_name: api
    restart: always
    build:
      context: ./api
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - 5000:5000

  www:
    image: www
    build:
      context: ./www
    container_name: www
    stdin_open: true
    volumes:
      - myshare:/usr/src/app/build
    container_name: www
    restart: always

volumes:
  mongodb-data:
  myshare:

networks:
  express-mongo:
  react-express:
