version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017

  api:
    image: api
    container_name: api
    restart: always
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - 5000:5000

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    build:
      context: ./www
    ports:
      - '8080:8080'
    volumes:
      - site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - react-express
      - express-mongo

volumes:
  mongodb-data:
  caddy_data:
  caddy_config:
  site:

networks:
  express-mongo:
  react-express:
